"""Replace ExpenseBudget with CategoryBudget

Revision ID: 9c19878bbb15
Revises: bc19d2819472
Create Date: 2025-08-29 01:11:33.445695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c19878bbb15'
down_revision: Union[str, None] = 'bc19d2819472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_budgets_id'), 'category_budgets', ['id'], unique=False)
    op.drop_index('ix_expense_budgets_id', table_name='expense_budgets')
    op.drop_table('expense_budgets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_budgets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('expense_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('budget', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], name='expense_budgets_expense_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='expense_budgets_pkey')
    )
    op.create_index('ix_expense_budgets_id', 'expense_budgets', ['id'], unique=False)
    op.drop_index(op.f('ix_category_budgets_id'), table_name='category_budgets')
    op.drop_table('category_budgets')
    # ### end Alembic commands ###
