"""add_is_active_field_to_category_budgets

Revision ID: a078096074ea
Revises: 96e066a6b6fb
Create Date: 2025-09-08 15:45:41.501951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a078096074ea'
down_revision: Union[str, None] = '96e066a6b6fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_budgets', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_budgets', 'is_active')
    # ### end Alembic commands ###
